name: Build and deploy

on:
  push:
    branches: master
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build haddocks
        run: nix develop --command bash -c 'nix build && ./result/bin/haddock'

      - name: Upload haddocks
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./miso-lynx/haddocks

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

